// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Subscribe(target string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><form action=\"#\" class=\"container flex flex-col gap-y-5\" hx-post=\"/subscribe\" hx-target=\"#modal-content\"><h2 class=\"font-extrabold\">Subscribe to the Newsletter!</h2><p class=\"font-medium\">Sign Up to the Newsletter and get the latest posts.</p><div class=\"relative\"><svg class=\"absolute top-0 left-2 bottom-0 mt-auto mr-0 mb-auto ml-0\" width=\"24px\" height=\"24px\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" color=\"#deded8\"><g clip-path=\"url(#clip0_2476_13290)\"><path d=\"M22.1525 3.55321L11.1772 21.0044L9.50686 12.4078L2.00002 7.89795L22.1525 3.55321Z\" stroke=\"#deded8\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path><path d=\"M9.45557 12.4436L22.1524 3.55321\" stroke=\"#deded8\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path></g><defs><clipPath id=\"clip0_2476_13290\"><rect width=\"24\" height=\"24\" fill=\"white\"></rect></clipPath></defs></svg> <input autofocus autocomplete=\"off\" class=\"pl-9 md:block bg-zinc-900 text-sm font-medium text-zinc-300 rounded-full w-full\" type=\"email\" name=\"email\" placeholder=\"your@email.com\" required></div><button type=\"submit\" class=\"text-zinc-300 bg-zinc-700 hover:text-white rounded-md text-sm p-2 font-medium self-center\">Subscribe</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
